### PR TITLE
Remove top level included

### PR DESCRIPTION
**Pull request by alexshook**
See commit messages for more details.

### CODE REVIEW

**Review by inactdev — COMMENTED** [review]
NO MORE INCLUDED EXPOSURES THO ??!!!

**Review by inactdev — CHANGES_REQUESTED** [review]
I don't think we can do this.  The Gandalf ACL depends on included exposures 😢

**Comment by alexshook** [comment]
😭

**Comment by alexshook** [comment]
@chandeeland this is true, I have seen it with my own eyes. I'll work on a different solution.

**Pull request closed without merging**
